import calculator
n1=int(input("Enter 1st number :"))
n2=int(input("Enter 2nd number:"))
a=calculator.sum(n1,n2)
s=calculator.sub(n1,n2)
m=calculator.mul(n1,n2)
d=calculator.divi(n1,n2)
fd=calculator.floordivi(n1,n2)
r=calculator.rem(n1,n2)
print("Addition of {} and {} is :{}".format(n1,n2,a))
print("subtraction of {} and {} is :{}".format(n1,n2,s))
print("Multiplication of {} and {} is :{}".format(n1,n2,m))
print("Division of {} and {} is :{}".format(n1,n2,d))
print("Floordivision of {} and {} is :{}".format(n1,n2,fd))
print("Reminder of {} and {} is :{}".format(n1,n2,r))
