from tkinter import *
win=Tk()
win.title("LOgin page")
win.minsize(width=200,height=400)
win.maxsize(width=400,height=500)
l1=Label(win,text="your name")
l1.place(x=0,y=10)
name=StringVar()
def edtech():
    x=name.get()
    print(x)
    l2.config(text=x,bg="yellow",fg="blue")
e1=Entry(win,width=20,textvariable=name)
e1.place(x=50,y=10)
b1=Button(win,text="ENTER",bg="green",fg="blue",command=edtech)
b1.place(x=50,y=50)
l2=Label(win,text="nothing",fg="black",bg="green")
l2.place(x=50,y=60)
win.mainloop()